--CREATING A INDEX

CREATE INDEX INDX_STAFF_FNAME
ON STAFF(FNAME);

--TO VIEW RESULTS

SELECT * FROM STAFF
WHERE FNAME LIKE 'A%';

--TO VIEW THE INDEX
SELECT * FROM USER_INDEXES;

--CREATING COMPOSITE INDEX
CREATE INDEX INX_STAFF_FNAME_LNAME
ON STAFF (FNAME, LNAME);