SELECT * FROM BRANCH;
SELECT * FROM STAFF;
SELECT * FROM PROPERTYRENT;
SELECT * FROM CLIENT;
SELECT * FROM PRIVATEOWNER;
SELECT * FROM VIEWING;

-- LIST THE SALARY AFTER ADDING 10%
--AS IS OPTIONAL , WE PUT "" IF WE WANT TO PUT A SPACE IN THE NAME
SELECT SALARY , SALARY*1.1 AS NEW_SALARY, FNAME "FIRST NAME"  
FROM STAFF;

SELECT B.*, S.* -- alias TO MAKE A SHORTCUT NAME IF THE NAME IS LONG 
FROM STAFF S, BRANCH B;

-- LIST 1ST AND LAST NAME FROM STAFF

SELECT FNAME,LNAME;
FROM STAFF;

--LIST ALL STAFF INFO 
SELECT  *
FROM STAFF
-- OR
SELECT  STAFFNO, FNAME, LNAME, POSITION, SEX, DOB, SALARY, BRANCHNO;
FROM STAFF

--LIST ALL THE PROPERTYFORRENT
SELECT *
FROM PROPERTYFORRENT;

-- LIST STREET AND NUMBER OF ROOMS IN EACH PROPERTY
SELECT STREET 

-- DISTINCT --> TO ELIMINATE REPITITION (SHOWS THE REPAETED VALUE ONLY ONCE)
SELECT DISTINCT PROPERTYNO
FROM VIEWING;

-- ORDERING
SELECT *
FROM STAFF
ORDER BY FNAME DESC;

SELECT *
FROM STAFF
WHERE SALARY > 20000

SELECT * FROM BRANCH
WHERE CITY = 'London' OR CITY = 'Glasgow';
-- WE CAN USE 'UPPER'

SELECT *
FROM STAFF 
WHERE SALARY BETWEEN 20000 AND 30000

SELECT *
FROM STAFF
WHERE FNAME LIKE '%n';
WHERE FNAME LIKE 'J%';
WHERE FNAME LIKE '%a%';

SELECT * FROM PRIVATEOWNER
WHERE FNAME LIKE 'J__'
WHERE ADDRESS LIKE '%St%'

SELECT *
FROM VIEWING
WHERE VCOMMENT IS NOT NULL

SELECT PROPERTYNO, TYPE , RENT
FROM PROPERTYFORRENT
ORDER BY TYPE, RENT DESC